version: '3'
services:
  jmeter:
    image: justb4/jmeter:latest
    volumes:
      - ./test.jmx:/jmeter/test.jmx
      - ./results:/jmeter/results
    command: -n -t /jmeter/test.jmx -l /jmeter/results/testresults.jtl -Jhost=localhost -Jport=50051 -Jusers=10 -Jduration=60 -Jrampup=10 -Jprotocol=grpc
