name: JMeter Test

on:
  push:
    branches: [ main ]

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.4.3.tgz
          tar -xzf apache-jmeter-5.4.3.tgz

      - name: Build the gRPC API server
        run: |
          go build -o grpc-server cmd/server/main.go

      - name: Start the gRPC API server
        run: |
          ./grpc-server &
          sleep 5

      - name: Run JMeter tests
        run: |
          ./apache-jmeter-5.4.1/bin/jmeter \
            -n \
            -t jmeter/test-plan.jmx \
            -l jmeter/test-results.jtl \
            -Jgrpc.host=localhost \
            -Jgrpc.port=50051 \
            -Jgrpc.test.request.payload.filepath=jmeter/test-request.json

      - name: Print JMeter test results
        run: cat jmeter/test-results.jtl
